name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache clojure/java dependencies
      uses: "actions/cache@v2"
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.deps.clj
        key: "${{ runner.os }}-clojure-${{ hashFiles('deps.edn') }}"
        restore-keys: "${{ runner.os }}-clojure-"

    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@master
      with:
        cli: '1.11.1.1208'

    - name: Build
      run: clojure -M:dev -m figwheel.main -O advanced -bo dev

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dev-resources/public
